CadeMeuMedico/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models; // Criação da instância
using System.Data.Entity;

namespace CadeMeuMedico.Controllers
{
    public class MedicosController : Controller
    {
        private EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();
        //
        // GET: /Medicos/

        public ActionResult Index()
        {
            var medicosList = db.Medicos.Include(m => m.Cidades).Include(m => m.Especialidades).ToList();
            return View(medicosList);
        }

        public ActionResult Adicionar()
        {
            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome");
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome");
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Medicos medico)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medico);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDCidade = new SelectList(db.Cidades, "IDCidade", "Nome", medico.IDCidade);
            ViewBag.IDEspecialidade = new SelectList(db.Especialidades, "IDEspecialidade", "Nome", medico.IDEspecialidade);
            return View(medico);
        }
    }
}

CadeMeuMedico/Views/App.cshtml
@{
    ViewBag.App = "Cadê Meu Médico ?";
}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.App - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.min.css")"
          rel="stylesheet" />
    <style>
        body {
            padding-top: 60px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">@ViewBag.App</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li id="menuPaises">
                        @Html.ActionLink("Médicos", "Index", "Medicos")
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <script src="@Url.Content("~/Scripts/jquery-3.1.0.min.js")">
    </script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")">
    </script>
    @RenderSection("script", required: false);
</body>
</html>